main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

news/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.news_home, name='news_home'),
    path('create', views.create, name='create'),
    path('createPost', views.redirectToCreatePost, name='createPost'),
    path('<int:pk>',views.NewsDetailView.as_view(), name='news_detail'),
    path('<int:pk>/update',views.NewsUpdateView.as_view(), name='news_update'),
    path('<int:pk>/delete',views.NewsDeleteView.as_view(), name='news_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
path('user/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils import timezone

class Articles(models.Model):
    title = models.CharField(
        'Название',
        max_length= 50,
        validators=[
            MinLengthValidator(4, 'Название должно быть не менее 4 символов'),
            MaxLengthValidator(50, 'Название должно быть не более 50 символов')
        ]
    )
    anons = models.CharField(
        'Анонс',
        max_length=100,
        validators=[
            MaxLengthValidator(100, 'Анонс должен быть не более 100 символов')
        ]
    )
    full_text = models.TextField(
        'Статья',
        validators=[
            MinLengthValidator(50, 'Статья должна быть не менее 50 символов')
        ]
    )
    image = models.ImageField(upload_to='uploads_model/', null=True, blank=True)
    date = models.DateTimeField('Дата публикации', default=timezone.now)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/news/{self.id}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image_profile = models.ImageField(upload_to='profile_images', null=True, blank=True)

news/forms.py
from .models import Articles
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea, FileInput

class ArticlesForm(ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'anons','full_text','image']

        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название статьи'
            }),
            'anons': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Анонс статьи'
            }),
            'full_text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст статьи'
            }),
            'image': FileInput(attrs={
                'class': 'form-control',
                'placeholder': 'Изображение'
            })
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    image_profile = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': True}))


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image_profile', 'username', 'email')

main/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'main/index.html')

news/views.py
from django.shortcuts import render, redirect
from .models import Articles
from .forms import ArticlesForm
from django.views.generic import DetailView, UpdateView, DeleteView


def news_home(request):
    news = Articles.objects.order_by('-date')
    return render(request,'news/news_home.html', {'news': news})

class NewsDetailView(DetailView):
    model = Articles
    template_name = 'news/detail_view.html'
    context_object_name = 'article'

class NewsUpdateView(UpdateView):
    model = Articles
    template_name = 'news/news_update.html'
    form_class = ArticlesForm

class NewsDeleteView(DeleteView):
    model = Articles
    success_url = '/news'
    template_name = 'news/news_delete.html'

def redirectToCreatePost(req):
    return render(req,'news/create.html')

def create(request):
    if request.method == 'POST':
        form = ArticlesForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('news_home')

    data = {
        'form': form
    }
    return render(request,'news/create.html', data)

users/views.py
from django.shortcuts import render,redirect
from .models import User
from .forms import UserLoginForm, UserRegisterForm, UserProfileForm
from django.contrib import auth


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return redirect('news_home')

    else:
        form = UserLoginForm()
    context = {
        'form': form
    }

    return render(request,'users/login.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        else:
            print(form.errors)
    else:
        form = UserRegisterForm()
    context = {
        'form': form
    }
    return render(request,'users/register.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('profile')
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request,'users/profile.html', context)

main/templates/main/index.html
{% extends 'main/layout.html' %}
{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="features">
        <h1>Главная страница</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eius eligendi error expedita laudantium obcaecati sed veniam vitae voluptas voluptate?</p>
    </div>
{% endblock %}

main/templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/logo.png' %}" alt="Лого">
        <span class="logo">Web</span>
        <h3>Навигация</h3>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}">Профиль</a></li>
            <li><a href="">Выйти</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Войти</a></li>
            <li><a href="{% url 'register' %}">Регистрация</a></li>
            {% endif %}
            <li><a href="{% url 'home' %}"><i class="fas fa-home"></i>Главная</a></li>
            <li><a href="{% url 'news_home' %}"><i class="fas fa-newspaper"></i>Новости</a></li>
            <li><a href="{% url 'createPost' %}"><i class="fas fa-plus-circle"></i>Добавить запись</a></li>
        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

news/templates/news/create.html
{% extends 'main/layout.html' %}
{% block title %}Форма по добавлению статьи{% endblock %}
{% block content %}
    <div class="features">
        <h1>Форма по добавлению статьи</h1>
        <form method="post" action="create" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="title" class="form-control" placeholder="Название статьи" maxlength="50" required id="id_title"><br>
            <input type="text" name="anons" class="form-control" placeholder="Анонс статьи" maxlength="250" required id="id_anons"><br>
            <textarea name="full_text" cols="40" rows="10" class="form-control" placeholder="Текст статьи" required id="id_full_text"></textarea><br>
            <input type="file" name="image" class="form-control" placeholder="Изображение" required id="id_image"><br>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <button class="btn btn-success" type="submit">Добавить статью</button>
        </form>
    </div>
{% endblock %}

news/templates/news/detail_view.html
{% extends 'main/layout.html' %}
{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ article.title }}</h1>
        <p>{{ article.date }}</p>
        <p>{{ article.full_text }}</p>
        {% if article.image %}
         <div>
             <p><img src="{{ article.image.url }}" width="200"></p>
         </div>
     {% endif %}
        <a href="{% url 'news_delete' article.id %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'news_update' article.id %}" class="btn btn-info">Редактировать</a>
    </div>
{% endblock %}

news/templates/news/news_delete.html
{% extends 'main/layout.html' %}
{% block title %}Удаление статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Удаление статьи</h1>
        <form method="post">
            {% csrf_token %}

            <button class="btn btn-success" type="submit">Удалить статью</button>
        </form>
    </div>
{% endblock %}

news/templates/news/news_home.html
{% extends 'main/layout.html' %}
{% block title %}Новости на сайте{% endblock %}

{% block content %}
    <div class="features">
        <h1>Новости на сайте</h1>
        {% if news %}
            {% for el in news %}
                <div class="alert alert-warning">
                    <h3>{{ el.title }}</h3>
                    <p>{{ el.anons }}</p>
                    <a href="{% url 'news_detail' el.id %}" class="btn btn-warning">Читать дальше</a>
                </div>
            {% endfor %}
        {% else %}
            <p>У вас нет записей!</p>
        {% endif %}

        {# Комментарий #}
    </div>
{% endblock %}

news/templates/news/news_update.html
{% extends 'main/layout.html' %}
{% block title %}Редактирование статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Редактирование статьи</h1>
        <form method="post" action="update" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="title" class="form-control" value="{{ form.title }}" maxlength="50" required id="id_title"><br>
            <input type="text" name="anons" class="form-control" value="{{ form.anons }}" maxlength="250" required id="id_anons"><br>
            <textarea name="full_text" cols="40" rows="10" class="form-control" value="{{ form.full_text }}" required id="id_full_text"></textarea><br>
            <input type="file" name="image" class="form-control" value="{{ form.image }}" required id="id_image"><br>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <button class="btn btn-success" type="submit">Редактировать</button>
        </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/layout.html' %}
{% block title %}Форма по добавлению статьи{% endblock %}
{% block content %}
    <div class="features">
        <h1>Войти</h1>
        <form method="post" action="login">
            {% csrf_token %}
            <input type="text" name="username" class="form-control" placeholder="Имя пользователя" required id="id_username"><br>
            <input type="password" name="password" class="form-control" placeholder="Пароль" required id="id_password"><br>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <button class="btn btn-success" type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Профиль{% endblock %}
{% block content %}
    <div class="features">
        <h1>Профиль</h1>
        <form method="post" action="profile" enctype="multipart/form-data">
            {% csrf_token %}
            {% if user.image_profile %}
                <div>
                    <p><img src="{{ user.image_profile.url }}" width="200"></p>
                </div>
            {% else %}
                <div>
                    <p><img src="{% static 'main/img/1.png' %}" width="200"></p>
                </div>
            {% endif %}
            <input type="text" name="first_name" class="form-control" value="{{ user.first_name }}" required id="id_first_name"><br>
            <input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" required id="id_last_name"><br>
            <input type="text" name="username" class="form-control" value="{{ user.username }}" id="id_username"><br>
            <input type="text" name="email" class="form-control" value="{{ user.email }}" id="id_email"><br>
            <input type="file" name="image_profile" class="form-control" required id="id_image_profile"><br>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            {{ error }}
            <button class="btn btn-success" type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/layout.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="features">
        <h1>Регистрация</h1>
        <form method="post" action="register">
            {% csrf_token %}
            <input type="text" name="first_name" class="form-control" placeholder="Имя" required id="id_first_name"><br>
            <input type="text" name="last_name" class="form-control" placeholder="Фамилия" required id="id_last_name"><br>
            <input type="text" name="username" class="form-control" placeholder="Логин" required id="id_username"><br>
            <input type="text" name="email" class="form-control" placeholder="Email" required id="id_email"><br>
            <input type="text" name="password1" class="form-control" placeholder="Пароль" required id="id_password1"><br>
            <input type="text" name="password2" class="form-control" placeholder="Подтверждение пароля" required id="id_password2"><br>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <button class="btn btn-success" type="submit">Зарегистрироваться</button>
        </form>
    </div>
{% endblock %}